add all-language-lexical languages
kiteco/atom-plugin pull request #692
Opened 2020-10-06 22:20 UTC by ryantberg

kiteco/kiteco#11791

2020-10-06 22:47 UTC, edzkite requested changes

2020-10-06 22:47 UTC, edzkite commented on lib/editors.js
>  const EXTENSIONS_BY_LANGUAGES = {
Is this list standard across all the editors? Any reason to not expose an endpoint in Kited to get this list?

2020-10-06 23:04 UTC, ryantberg commented on lib/editors.js
>  const EXTENSIONS_BY_LANGUAGES = {
I believe the issue with that is if the Kite Engine isn't installed/running, the status bar wouldn't be present to inform the user of that.

2020-10-06 23:29 UTC, edzkite commented on lib/editors.js
>  const EXTENSIONS_BY_LANGUAGES = {
Good point.

However, if we're switching to an all language world, wouldn't it make more sense to invert the logic so that the Kite status is always visible, unless the current file type is unsupported?

With the current approach, updating the languages we support means we would have to go through all our editors and update them individually. Ideally, we should minimize the chance of small diffs in behavior between editors.

On the other hand, we could do more work upfront, but save a lot of headaches in the future.

2020-10-07 18:42 UTC, ryantberg commented on lib/editors.js
>  const EXTENSIONS_BY_LANGUAGES = {
I think that approach requires enough investigation that it should be considered separately from the ALL release, and I'm not sure if it is worth the complication unless we start changing language support dynamically or at a much higher frequency than we currently do.

2020-10-07 20:12 UTC, merged